### ISSUE TITLE
Possible build fail fix for snake action

### ISSUE THREAD

**Issue by samvictordr** [Varun-Govindasamy/Varun-Govindasamy#2]
I think that read-write permissions for github-actions aren't granted to this git. This could be fixed by navigating to the Repository's Settings -> Actions -> General -> Workflow permissions
![A5EEk](https://github.com/Varun-Govindasamy/Varun-Govindasamy/assets/105478252/070ca8e8-0de9-40a1-8769-5b20e80beafe)

This fix is consistent with the build fail occur that we get thrown when we run the action:
<img width="994" alt="Screenshot 2024-01-31 at 11 23 02 PM" src="https://github.com/Varun-Govindasamy/Varun-Govindasamy/assets/105478252/4a013037-3645-4a4d-ba69-9ca7fa808bbe">

**Comment by Varun-Govindasamy** [comment]
ok lemme check with that

**Comment by Varun-Govindasamy** [comment]
Yay, lass goooo!! it worked!! Thanks man

**Comment by samvictordr** [comment]
aye g, happy to helpe✌🏻
